# Generated by Django 5.2.8 on 2025-11-22 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('INGRESO', 'Ingreso (Sueldo, Bono, Extra)'), ('EGRESO', 'Egreso (Retención, Impuesto, Adelanto)')], max_length=7)),
                ('es_calculado', models.BooleanField(default=False, help_text='Indica si el monto debe ser calculado por el sistema (ej: Horas Extra) o es un valor fijo.')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_inicio_periodo', models.DateField()),
                ('fecha_fin_periodo', models.DateField()),
                ('monto_bruto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente de Revisión'), ('APRO', 'Aprobada/Lista para Pago'), ('PAG', 'Pagada'), ('CANC', 'Cancelada')], default='PEND', max_length=4)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liquidaciones', to='personal.empleado')),
            ],
            options={
                'unique_together': {('empleado', 'fecha_inicio_periodo', 'fecha_fin_periodo')},
            },
        ),
        migrations.CreateModel(
            name='DetalleLiquidacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nomina.conceptonomina')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='nomina.liquidacion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
