# Generated by Django 5.2.8 on 2025-11-21 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('capacidad_maxima', models.PositiveSmallIntegerField(default=2)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_convertible', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True, verbose_name='Número de Habitación')),
                ('piso', models.CharField(choices=[('PB', 'Planta Baja'), ('1', 'Primer Piso'), ('2', 'Segundo Piso'), ('3', 'Tercer Piso'), ('4', 'Cuarto Piso')], max_length=2)),
                ('estado_ocupacion', models.CharField(choices=[('L', 'Libre'), ('R', 'Reservada'), ('O', 'Ocupada')], default='L', max_length=1, verbose_name='Estado de Ocupación')),
                ('estado_servicio', models.CharField(choices=[('L', 'Limpia'), ('S', 'Sucia'), ('E', 'En Limpieza'), ('M', 'En Mantenimiento')], default='L', max_length=1, verbose_name='Estado de Limpieza/Servicio')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='habitaciones.tipohabitacion')),
            ],
        ),
    ]
