# Generated by Django 5.2.8 on 2025-11-22 03:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('ABT', 'Abierta'), ('CERR', 'Cerrada'), ('PAG', 'Pagada')], default='ABT', max_length=4)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta', to='reservas.reserva', verbose_name='Reserva Asociada')),
            ],
            options={
                'verbose_name': 'Cuenta de Huésped',
                'verbose_name_plural': 'Cuentas de Huéspedes',
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('CARGO', 'Cargo (Consumo/Tarifa)'), ('PAGO', 'Pago (Efectivo/Tarjeta)')], max_length=5)),
                ('concepto', models.CharField(help_text='Detalle del cargo o pago (Ej: Tarifa, Restaurante, Depósito, Lavandería).', max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto de la transacción.', max_digits=10)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='cuentas.cuenta', verbose_name='Cuenta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
