# Generated by Django 5.2.8 on 2025-11-22 04:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('huespedes', '0001_initial'),
        ('reservas', '0002_remove_reserva_habitacion_alter_reserva_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('checkin_timestamp', models.DateTimeField(blank=True, null=True)),
                ('checkout_timestamp', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente Check-In'), ('ACT', 'Activa (Huéspedes en habitación)'), ('FINAL', 'Finalizada (Check-Out completo)')], default='PEND', max_length=5)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadias', to='habitaciones.habitacion', verbose_name='Habitación Asignada')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='reservas.reserva', verbose_name='Reserva Padre')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HuespedEstadia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si esta persona es el responsable principal de la habitación.')),
                ('estadia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocupantes', to='recepcion.estadia', verbose_name='Estadía Asociada')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estadias_ocupadas', to='huespedes.huesped', verbose_name='Huésped')),
            ],
            options={
                'verbose_name': 'Ocupante de Estadía',
                'verbose_name_plural': 'Ocupantes de Estadía',
                'unique_together': {('estadia', 'huesped')},
            },
        ),
    ]
