# Generated by Django 5.2.8 on 2025-11-22 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habitaciones', '0001_initial'),
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_checkin', models.DateField(verbose_name='Fecha de Check-In')),
                ('fecha_checkout', models.DateField(verbose_name='Fecha de Check-Out')),
                ('precio_estimado', models.DecimalField(decimal_places=2, help_text='Precio total de la estadía sin incluir extras.', max_digits=10)),
                ('estado', models.CharField(choices=[('PEN', 'Pendiente de Confirmación'), ('CONF', 'Confirmada'), ('CI', 'Check-In Realizado'), ('CO', 'Check-Out Realizado'), ('CANC', 'Cancelada'), ('NS', 'No Show')], default='PEN', max_length=4, verbose_name='Estado de la Reserva')),
                ('notas', models.TextField(blank=True, null=True)),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas', to='habitaciones.habitacion', verbose_name='Habitación Asignada')),
                ('huesped_titular', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservas_titulares', to='huespedes.huesped', verbose_name='Huésped Titular')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
    ]
