# Generated by Django 5.2.8 on 2025-11-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='habitacion',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('PEN', 'Pendiente de Confirmación'), ('CONF', 'Confirmada'), ('CI', 'Check-In Realizado'), ('CO', 'Check-Out Realizado'), ('CANC', 'Cancelada'), ('NS', 'No Show')], default='PEN', max_length=4),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='precio_estimado',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
